### ISSUE TITLE
spatial_index.query_point not working correctly for nodes which start hidden and then are shown

### ISSUE THREAD

**Issue by PawelRoman** [kaaengine/kaa#132]
1. Create a node X with a child node Y (both should have some sprites set), make sure that the node has visible=False, i.e. is hidden
2. Add node X to scene
3. On update() set visible=True on node X and change it's position (both need to happen during the same frame!). Then let the app run and on any subsequent update run spatial_index.query_point() on a point where node Y is showing up.

Expected: query_point should return the node Y
Actual: query_point does not return the node Y

Attaching an example here: [query_point.zip](https://github.com/kaaengine/kaa/files/7628993/query_point.zip)

Steps to replicate:
1) Press space bar to show previously hidden node
2) Click on newly shown child node (green area)

Expected - Child node is returned by query_point
Actual - it is not returned!!

**Comment by mmicek** [comment]
Fixed
