### ISSUE TITLE
Collision queries

### ISSUE THREAD

**Issue by PawelRoman** [kaaengine/kaa#33]
Expose active querying for chipmunk collisions to python layer. 

Function should accept a shape (segment, circle, polygon etc.) and return a list of tuples (colliding_node, colliding_hitboxes) where colliding node should be actual node instance that colides and hitboxes should be hitboxes (can be more than one) belonging to that node which collided.

**Comment by maniek2332** [comment]
Implemented by `SpaceNode.query_shape_overlaps()`
