### ISSUE TITLE
Playing sound effects in a loop, with ability to interrupt it at any moment

### ISSUE THREAD

**Issue by PawelRoman** [kaaengine/kaa#41]
Suppose I have a short sfx file which is designed to be played in a loop - it is a sound of footsteps.

As player moves the character around the screen I want that footsteps sound to be played in a loop. When player stops moving (which can be in the middle of the loop) I want the sfx to stop playing immediately.

Please add support for this use case.

**Comment by maniek2332** [comment]
implemented by `SoundPlayback`
