### ISSUE TITLE
Ability to hide mouse cursor and show custom cursor (as Node)

### ISSUE THREAD

**Issue by PawelRoman** [kaaengine/kaa#93]
Suggested API:

Add MouseManager.cursor property. Make it read/write. 

Default value is None. None value works like now - shows system cursor.

MouseManager.cursor accepts a Node instance. When setting it to a Node, system cursor is hidden, replaced with image shown by the node. origin_alignment of the node should set the active 'pixel' of the node (the pixel whose position is 'click' position). It should be possible for this node to have transitions, animations and other normal features of a Node.

**Comment by labuzm** [comment]
You can use MouseManager.coursor_visible property to control mouse cursor visibility.
